scen <- list(list(type = "NormalExercise", student = "\n  summary(c(1,2,3,4))", solution = "\n  summary(c(1,2,3,4),c(1,2,3,4))\n  dim(c(1,2,3))", 
    pass = list(test_basic_check_pass_1 = list(long = "basic function check - pass 1", sct = "test_function(\"summary\")")), 
    fail = list(test_basic_check_fail_1 = list(long = "basic function check - fail 1", sct = "test_function(\"dim\")"), 
        test_not_called_msg_fail_1 = list(long = "check if not_called_msg feedback is correct - fail 1", sct = "test_function(\"dim\", not_called_msg = \"This is the not called message\")", 
            message = "This is the not called message"))), list(type = "NormalExercise", student = "\n  summary(c(1,2,3,4))\n  dim(c(1,2,3))\n  rep(1, 4)\n  dnorm(1, 10, 5)\n  mean(c(1,2,3), na.rm = FALSE)", 
    solution = "\n  summary(c(1,2,3,4))\n  dim(c(1,2,3,4))\n  rep(1, 20)\n  dnorm(1,10)\n  mean(c(1,2,3), na.rm = TRUE)", 
    pass = list(test_arguments_pass_1 = list(long = "checks on the function arguments - pass 1", sct = "test_function(\"summary\", \"object\")"), 
        test_arguments_pass_2 = list(long = "checks on the function arguments - pass 2", sct = "test_function(\"rep\", \"x\")"), 
        test_arguments_pass_3 = list(long = "checks on the function arguments - pass 3", sct = "test_function(\"dnorm\", c(\"x\", \"mean\"))")), 
    fail = list(test_arguments_fail_1 = list(long = "checks on the function arguments - fail 1", sct = "test_function(\"dim\", \"x\")"), 
        test_arguments_fail_2 = list(long = "checks on the function arguments - fail 2", sct = "test_function(\"dnorm\", c(\"x\", \"mean\"), allow_extra = FALSE)"), 
        test_arguments_fail_3 = list(long = "checks on the function arguments - fail 3", sct = "test_function(\"mean\", c(\"x\", \"na.rm\"))"), 
        test_incorrect_msg_fail_1 = list(long = "check if incorrect_msg feedback is correct - fail 1", sct = "test_function(\"dim\", \"x\", incorrect_msg = \"This is the incorrect message\")", 
            message = "This is the incorrect message"))), list(type = "NormalExercise", student = "\n  df.equiv <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6))\n  var(df.equiv)\n  df.not_equiv <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6))\n  lm(df.not_equiv)", 
    solution = "\n  df.equiv <- data.frame(c = c(1, 2, 3), d = c(4, 5, 6))\n  var(df.equiv)\n  df.not_equiv <- data.frame(c = c(7, 8, 9), d = c(4, 5, 6))\n  lm(df.not_equiv)", 
    pass = list(test_equal_pass_1 = list(long = "difference between equal and equivalent for arguments - pass 1", 
        sct = "test_function(\"var\", \"x\")")), fail = list(test_equal_fail_1 = list(long = "difference between equal and equivalent for arguments - fail 1", 
        sct = "test_function(\"lm\", \"formula\")"), test_equal_fail_2 = list(long = "difference between equal and equivalent for arguments - fail 2", 
        sct = "test_function(\"var\", \"x\", eq_condition = \"equal\")"), test_equal_fail_3 = list(long = "difference between equal and equivalent for arguments - fail 3", 
        sct = "test_function(\"lm\", \"formula\", eq_condition = \"equal\")"))), list(type = "NormalExercise", 
    student = "\n  df.equiv <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6))\n  var(df.equiv)\n  df.not_equiv <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6))\n  lm(df.not_equiv)", 
    solution = "\n  df.equiv <- data.frame(c = c(1, 2, 3), d = c(4, 5, 6))\n  var(df.equiv)\n  df.not_equiv <- data.frame(c = c(7, 8, 9), d = c(4, 5, 6))\n  lm(df.not_equiv)", 
    pass = list(test_equal_pass_1 = list(long = "difference between equal and equivalent for arguments - pass 1", 
        sct = "test_function(\"var\", \"x\")"), test_equal_pass_2 = list(long = "difference between equal and equivalent for arguments - pass 2", 
        sct = "test_function(\"var\", eval = FALSE)"), test_equal_pass_3 = list(long = "difference between equal and equivalent for arguments - pass 3", 
        sct = "test_function(\"lm\", eval = FALSE)"), test_equal_pass_4 = list(long = "difference between equal and equivalent for arguments - pass 4", 
        sct = "test_function(\"var\", eval = FALSE, eq_condition = \"equal\")"), test_equal_pass_5 = list(long = "difference between equal and equivalent for arguments - pass 5", 
        sct = "test_function(\"lm\", eval = FALSE, eq_condition = \"equal\")")), fail = list(test_equal_fail_1 = list(long = "difference between equal and equivalent for arguments - fail 1", 
        sct = "test_function(\"lm\", \"formula\")"), test_equal_fail_2 = list(long = "difference between equal and equivalent for arguments - fail 2", 
        sct = "test_function(\"var\", \"x\", eq_condition = \"equal\")"), test_equal_fail_3 = list(long = "difference between equal and equivalent for arguments - fail 3", 
        sct = "test_function(\"lm\", \"formula\", eq_condition = \"equal\")"))), list(type = "NormalExercise", 
    student = "\n  var.iden <- 3\n  var(var.iden)\n  var.equal <- 4\n  mean(var.equal)", solution = "\n  var.iden <- 3 + 4.4e-8\n  var(var.iden)\n  var.equal <- 4\n  mean(var.equal)", 
    pass = list(test_identical_pass_1 = list(long = "difference between identical and equal for arguments - pass 1", 
        sct = "test_function(\"var\", \"x\", eq_condition = \"equal\")"), test_identical_pass_2 = list(long = "difference between identical and equal for arguments - pass 2", 
        sct = "test_function(\"mean\", \"formula\", eq_condition = \"equal\")"), test_identical_pass_3 = list(long = "difference between identical and equal for arguments - pass 3", 
        sct = "test_function(\"mean\", \"formula\", eq_condition = \"identical\")"), test_identical_pass_4 = list(long = "difference between identical and equal for arguments - pass 4", 
        sct = "test_function(\"var\", eval = FALSE, eq_condition = \"equal\")"), test_identical_pass_5 = list(long = "difference between identical and equal for arguments - pass 5", 
        sct = "test_function(\"mean\", eval = FALSE, eq_condition = \"equal\")"), test_identical_pass_6 = list(long = "difference between identical and equal for arguments - pass 6", 
        sct = "test_function(\"var\", eval = FALSE, eq_condition = \"identical\")"), test_identical_pass_7 = list(long = "difference between identical and equal for arguments - pass 7", 
        sct = "test_function(\"mean\", eval = FALSE, eq_condition = \"identical\")")), fail = list(test_identical_fail_1 = list(long = "difference between identical and equal for arguments - fail 1", 
        sct = "test_function(\"var\", \"x\", eq_condition = \"identical\")"))), list(type = "NormalExercise", 
    student = "\n  var.a <- c(302, 305, 309)\n  mean(var.a)\n  var(var.a)", solution = "\n  var.b <- c(302, 305, 309)\n  mean(var.b)\n  var(var.b)", 
    pass = list(test_eval_pass_1 = list(long = "checks whether the eval argument works properly - pass 1", sct = "test_function(\"mean\", \"x\")")), 
    fail = list(test_eval_fail_1 = list(long = "checks whether the eval argument works properly - fail 1", sct = "test_function(\"var\", \"x\", eval = FALSE)"))), 
    list(type = "NormalExercise", student = "\n  mean(1:10, trim = 0.9)\n  var(1:5, 6:10)", solution = "\n  mean(1:10)\n  var(1:5, 6:10)", 
        pass = list(test_allow_extra_pass_1 = list(long = "checks whether the allow_extra argument works properly - pass 1", 
            sct = "test_function(\"mean\", \"x\")"), test_allow_extra_pass_2 = list(long = "checks whether the allow_extra argument works properly - pass 2", 
            sct = "test_function(\"mean\", c(\"x\", \"trim\"), allow_extra = FALSE)"), test_allow_extra_pass_3 = list(long = "checks whether the allow_extra argument works properly - pass 3", 
            sct = "test_function(\"var\", c(\"x\", \"y\"), allow_extra = FALSE)")), fail = list(test_allow_extra_fail_1 = list(long = "checks whether the allow_extra argument works properly - fail 1", 
            sct = "test_function(\"mean\", \"x\", allow_extra = FALSE)"))), list(type = "NormalExercise", student = "\n  mean(1:10, trim = 0.9, na.rm = FALSE)\n  var(1:5, 6:10)", 
        solution = "\n  mean(1:10)\n  var(1:5, 11:15)", pass = list(test_ignore_pass_1 = list(long = "checks whether the ignore argument works properly - pass 1", 
            sct = c("test_function(\"mean\", \"x\", allow_extra = FALSE, ignore = c(\"trim\", ", "    \"na.rm\"))")), 
            test_ignore_pass_2 = list(long = "checks whether the ignore argument works properly - pass 2", sct = "test_function(\"var\", \"x\", allow_extra = FALSE, ignore = \"y\")")), 
        fail = list(test_ignore_fail_1 = list(long = "checks whether the ignore argument works properly - fail 1", 
            sct = "test_function(\"mean\", \"x\", allow_extra = FALSE, ignore = \"na.rm\")"), test_ignore_fail_2 = list(long = "checks whether the ignore argument works properly - fail 2", 
            sct = "test_function(\"mean\", \"x\", allow_extra = FALSE, ignore = \"na.rm\")"))), list(type = "NormalExercise", 
        student = "\n  a <- \"test\"\n  mean(1:10, trim = 0.9, na.rm = FALSE)\n  mean(1:5, trim = 0.8)\n  mean(1:10, trim = 0.9)", 
        solution = "\n  a <- \"test\"\n  mean(1:10, trim = 0.9)\n  mean(1:9)\n  mean(1:10)", pass = list(test_index_old_pass_1 = list(long = "checks whether the index argument works properly - pass 1", 
            sct = "test_function(\"mean\", \"x\", index = 2)"), test_index_old_pass_2 = list(long = "checks whether the index argument works properly - pass 2", 
            sct = "test_function(\"mean\", c(\"x\", \"trim\"))")), fail = list(test_index_old_fail_1 = list(long = "checks whether the index argument works properly - fail 1", 
            sct = "test_function(\"mean\", \"x\", index = 3)"), test_index_old_fail_2 = list(long = "checks whether the index argument works properly - fail 2", 
            sct = "test_function(\"mean\", c(\"x\", \"trim\"), allow_extra = FALSE, index = 2)"), test_index_old_fail_3 = list(long = "checks whether the index argument works properly - fail 3", 
            sct = "test_function(\"mean\", \"x\", allow_extra = FALSE, index = 4)"))))
