scen <- list(list(type = "NormalExercise", student = "\n  var.equiv <- 3\n  var.not_equiv <- 4", solution = "\n  var.equiv <- 3\n  var.other_equiv <- 4\n  var.not_here <- 2\n  var.not_equiv <- 5", 
    fail = list(test_equivalence_fail_1 = list(long = "handle equivalence correctly - fail 1", sct = "test_an_object(\"var.not_equiv\", \"Testing 1\")"), 
        test_undefined_msg_fail_1 = list(long = "test on undefined message - fail 1", sct = "test_an_object(\"var.not_here\",  \"This is the undefined message\")", 
            message = "This is the undefined message")), pass = list(test_equivalence_pass_1 = list(long = "handle equivalence correctly - pass 1", 
        sct = "test_an_object(\"var.equiv\", \"Testing 2\")"), test_equivalence_pass_2 = list(long = "handle equivalence correctly - pass 2", 
        sct = "test_an_object(\"var.other_equiv\", \"Testing 3\")"))), list(type = "NormalExercise", student = "\n  df.equiv <- data.frame(a=c(10,11,12), b=c(4,5,6))\n  df.not_equiv <- data.frame(a=c(1,2,3), b=c(4,5,6))", 
    solution = "\n  df.equiv <- data.frame(c=c(1,2,3), d=c(4,5,6))\n  df.not_equiv <- data.frame(c=c(7,8,9), d=c(4,5,6))", 
    fail = list(test_equal_fail_1 = list(long = "difference between equals and equivalent - fail 1", sct = "test_an_object(\"df.equiv\", \"Testing 4\", eq_condition = \"equal\")"), 
        test_equal_fail_2 = list(long = "difference between equals and equivalent - fail 2", sct = "test_an_object(\"df.not_equiv\", \"Testing 6\", eq_condition = \"equal\")"), 
        test_equal_fail_3 = list(long = "difference between equals and equivalent - fail 3", sct = "test_an_object(\"df.not_equiv\", \"Testing 7\")")), 
    pass = list(test_equal_pass_1 = list(long = "difference between equals and equivalent - pass 1", sct = "test_an_object(\"df.equiv\", \"Testing 5\")"))), 
    list(type = "NormalExercise", student = "\n  var.iden <- 3 + 4.4e-8\n  var.equal <- 4", solution = "\n  var.iden <- 4\n  var.equal <- 3", 
        fail = list(test_identical_fail_1 = list(long = "difference between equals and identical - fail 1", sct = "test_an_object(\"var.equal\", \"Testing 8\", eq_condition = \"identical\")")), 
        pass = list(test_identical_pass_1 = list(long = "difference between equals and identical - pass 1", sct = "test_an_object(\"var.iden\", \"Testing 9\", eq_condition = \"identical\")"), 
            test_identical_pass_2 = list(long = "difference between equals and identical - pass 2", sct = "test_an_object(\"var.equal\", \"Testing 10\")"))))
