scen <- list(
  list(
    type = "NormalExercise", 
    student = "\n  var.equiv <- 3\n  var.not_equiv <- 4\n  mean(var.equiv)", 
    solution = "\n  var.equiv <- 3\n  var.not_equiv <- 3\n  var.not_here <- 2\n  mean(var.equiv)", 
    pass = list(
      test_check_correct_pass_1 = list(
        long = "test succeeds if check is correct and diagnose is correct - pass 1", 
        sct = c("test_correct({", "    test_object(\"var.equiv\")", "}, {", "    test_function(\"mean\")", "})")
      )
    )
  ), 
  
  list(
    type = "NormalExercise",
    student = "\n  var.equiv <- 3\n  var.not_equiv <- 4\n  mean(var.not_equiv)", 
    solution = "\n  var.equiv <- 3\n  var.not_equiv <- 3\n  var.not_here <- 2\n  mean(var.not_equiv)", 
    pass = list(test_diagnose_false_pass_1 = list(long = "test succeeds if check is correct and diagnose is false - pass 1", 
                                                  sct = c("test_correct({", 
                                                          "    test_object(\"var.equiv\")",
                                                          "    test_function(\"mean\")", 
                                                          "}, {", 
                                                          "    test_function(\"mean\", \"x\")", "})")))), 
  list(type = "NormalExercise", 
       student = "\n  var.equiv <- 3\n  var.not_equiv <- 4\n  mean(var.not_equiv)", 
       solution = "\n  var.equiv <- 3\n  var.not_equiv <- 3\n  var.not_here <- 2\n  mean(var.not_equiv)", 
       fail = list(test_check_false_fail_1 = list(long = "test fails if check is false and diagnose is correct - fail 1", 
                                                  sct = c("test_correct({", 
                                                          "    test_object(\"var.equiv\")", 
                                                          "    test_function(\"mean\", \"x\", incorrect_msg = \"This is the one\")",
                                                          "}, {",
                                                          "    test_function(\"mean\")", "})"),
                                                  message = "This is the one"),
                   test_check_false_fail_2 = list(long = "test fails if check is false and diagnose is correct - fail 2", 
                                                  sct = c("test_correct({", "    test_object(\"var.not_equiv\", incorrect_msg = \"Wrong object!\")", 
                "    test_function(\"mean\", \"x\", incorrect_msg = \"This is the one\")", "}, {", "    test_object(\"var.equiv\")", 
                "})"), message = "Wrong object!"))), list(type = "NormalExercise", 
                                                          student = "\n  var.equiv <- 3\n  var.not_equiv <- 4\n  mean(var.not_equiv)", 
        solution = "\n  var.equiv <- 3\n  var.not_equiv <- 3\n  var.not_here <- 2\n  mean(var.not_equiv)", 
        fail = list(test_check_diagnose_msg_fail_1 = list(long = "tests if the correct feedback is send for diangose - fail 1", 
                                                          sct = c("test_correct({", "    test_object(\"var.not_equiv\", incorrect_msg = \"Don't send this\")", 
                "}, {", "    test_function(\"mean\", \"x\", incorrect_msg = \"Diagnose of the problem\")", "})"), 
                message = "Diagnose of the problem"))), 
  list(type = "NormalExercise", 
       student = "\n  var.equiv <- 3\n  var.not_equiv <- 4\n  mean(var.not_equiv)", 
       solution = "\n  var.equiv <- 3\n  var.not_equiv <- 3\n  var.not_here <- 2\n  mean(var.not_equiv)", 
       fail = list(test_check_diagnose_msg_2_fail_1 = list(long = "tests if the correct feedback is send for diangose 2 - fail 1", 
                                                           sct = c("test_correct({", 
                                                                   "    test_object(\"var.not_equiv\", incorrect_msg = \"Don't send this\")", 
                                                                   "    test_object(\"var.equiv\")", "    test_function(\"mean\", \"x\", incorrect_msg = \"Wrong message\")", 
                                                                   "}, {", 
                                                                   "    test_function(\"mean\", not_called_msg = \"Diagnose of the problem\")", 
                                                                   "    test_function(\"mean\", \"x\", incorrect_msg = \"This is the one!\")", 
                                                                   "})"), 
                                                           message = "This is the one!"))), 
  list(type = "NormalExercise", 
       student = "\n  var.equiv <- 3\n  var.not_equiv <- 4\n  mean(var.not_equiv)", 
       solution = "\n  var.equiv <- 3\n  var.not_equiv <- 3\n  var.not_here <- 2\n  mean(var.not_equiv)", 
       fail = list(test_check_msg_fail_1 = list(long = "tests if the correct feedback is send for check - fail 1", 
                                                sct = c("test_correct({", 
                                                        "    test_object(\"var.not_equiv\", incorrect_msg = \"It will send this oneeee\")",
                                                        "    test_object(\"var.equiv\")", 
                                                        "    test_function(\"mean\", \"x\", incorrect_msg = \"Wrong message\")", 
                                                        "}, {", 
                                                        "    test_function(\"mean\", not_called_msg = \"Diagnose of the problem\")", "})"), 
                                                message = "It will send this oneeee"))))
