scen <- list(list(type = "NormalExercise", pre_exercise_code = "i <- 1", student = "\n  while (i < 10) {\n    rpois(10,i)\n    i = i + 1\n  }", 
    solution = "\n  while (i < 3) {\n    rnorm(10,i)\n    i = i + 1\n  }", pass = list(test_basic_check_pass_1 = list(long = "check whether basic test works - pass 1", 
        sct = "test_while_loop()"))), list(type = "NormalExercise", pre_exercise_code = "i = 1", solution = "\n  while (i < 3) {\n    rnorm(10,i)\n    i = i + 1\n  }", 
    fail = list(test_basic_check_fails_fail_1 = list(long = "check whether basic test fails if there is no for statement - fail 1", 
        sct = "test_while_loop()"))), list(type = "NormalExercise", pre_exercise_code = "i = 1", student = "\n  while (i < 10) {\n    rpois(10,i)\n    i = i + 1\n  }", 
    solution = "\n  while (i < 10) {\n    rpois(10,i)\n    i = i + 1\n  }", pass = list(test_cond_test_pass_1 = list(long = "check if cond_test is checked correctly - pass 1", 
        sct = c("test_while_loop(cond_test = {", "    test_object(\"i\")", "})")))), list(type = "NormalExercise", 
    pre_exercise_code = "i = 1", student = "\n  while (i < 10) {\n    rpois(10,i)\n    i = i + 1\n  }", solution = "n <- 4\n  while (i < 3) {\n    rpois(10,i)\n    i = i + 1\n  }", 
    fail = list(test_cond_test_fails_fail_1 = list(long = "check if cond_test fails correctly - fail 1", sct = c("test_while_loop(cond_test = {", 
        "    test_object(\"i\")", "})")), test_cond_test_fails_fail_2 = list(long = "check if cond_test fails correctly - fail 2", 
        sct = c("test_while_loop(cond_test = {", "    test_object(\"n\")", "})")), test_cond_test_msg_fail_1 = list(long = "check if cond_test fail message is displayed correctly - fail 1", 
        sct = c("test_while_loop(cond_test = {", "    test_object(\"i\", incorrect_msg = \"Wrong condition\")", 
            "})"), message = "Wrong condition"))), list(type = "NormalExercise", pre_exercise_code = "i = 1", student = "\n  while (i < 10) {\n    rpois(10,i)\n    i = i + 1\n  }", 
    solution = "\n  while (i < 10) {\n    rpois(10,i)\n    i = i + 1\n  }", pass = list(test_expr_test_pass_1 = list(long = "check if cond_test is checked correctly - pass 1", 
        sct = c("test_while_loop(expr_test = {", "    test_function(\"rpois\", c(\"n\", \"lambda\"))", "})")), 
        test_expr_test_pass_2 = list(long = "check if cond_test is checked correctly - pass 2", sct = c("test_while_loop(expr_test = {", 
            "    test_function(\"rpois\", c(\"n\", \"lambda\"))", "    test_object(\"i\")", "})")))), list(type = "NormalExercise", 
    pre_exercise_code = "i <- 1", student = "\n  while (i < 10) {\n    rpois(3,i)\n    i = i + 1\n  }", solution = "\n  while (i < 10) {\n    rpois(10,i)\n    rnorm(10,i)\n    i = i + 1\n  }", 
    fail = list(test_expr_test_fails_fail_1 = list(long = "check if expr_test fails correctly - fail 1", sct = c("test_while_loop(expr_test = {", 
        "    test_function(\"rpois\", c(\"n\", \"lambda\"))", "})")), test_expr_test_fails_fail_2 = list(long = "check if expr_test fails correctly - fail 2", 
        sct = c("test_while_loop(expr_test = {", "    test_function(\"rnorm\")", "})")), test_expr_test_msg_fail_1 = list(long = "check if cond_test fail message is displayed correctly - fail 1", 
        sct = c("test_while_loop(expr_test = {", "    test_function(\"rpois\", c(\"n\", \"lambda\"), incorrect_msg = \"Wrong expression\")", 
            "})"), message = "Wrong expression"))), list(type = "NormalExercise", student = "\n  i = 3\n  n = 3\n  while (i < 8) {\n    rpois(2,i)\n    i = i + 1\n  }\n  a <- \"some code here\"\n  while (n < 5) {\n    rnorm(5, n*n)\n    n = n + 1\n  }", 
    solution = "\n  i = 1\n  n = 3\n  while (i < 10) {\n    rpois(10,i)\n    i = i + 1\n  }\n  while (n < 5) {\n    rnorm(5, n*n)\n    n = n + 1\n  }", 
    pass = list(test_index_pass_1 = list(long = "check if index is checked correctly - pass 1", sct = c("test_while_loop(2, cond_test = {", 
        "    test_object(\"n\")", "}, expr_test = {", "    test_function(\"rnorm\", c(\"n\", \"lambda\"))", "})"))), 
    fail = list(test_index_fail_1 = list(long = "check if index is checked correctly - fail 1", sct = c("test_while_loop(1, expr_test = {", 
        "    test_function(\"rpois\", c(\"n\", \"lambda\"))", "})")), test_not_found_msg_fail_1 = list(long = "check if not_found_msg is displayed correctly - fail 1", 
        sct = "test_while_loop(3, not_found_msg = \"Too much looooooops\")", message = "Too much looooooops"))))
