scen <- list(list(type = "MarkdownExercise", student = "\n---\ntitle: \"Testing\"\n---\n    \n    This\n    is\n    a\n    test\n    \n    ```{r}\n    dim(cars)\n    ```", 
    solution = "\n---\ntitle: \"Testing\"\n---\n    \n    This\n    is\n    a\n    test\n    but\n    doesn't \n    matter\n    \n    ```{r}\n    str(cars)\n    ```", 
    pass = list(test_one_option_pass_1 = list(long = "test if one option is correctly recognized - pass 1", sct = "test_yaml_header(options = c(\"title\"))"))), 
    list(type = "MarkdownExercise", student = "\n---\ntitle: \"Testing\"\noutput: html_document\n---\n    \n    This\n    is\n    a\n    test\n    \n    ```{r}\n    dim(cars)\n    ```", 
        solution = "\n---\ntitle: \"Testing\"\noutput: html_document\n---\n    \n    This\n    is\n    a\n    test\n    but\n    doesn't \n    matter\n    \n    ```{r}\n    str(cars)\n    ```", 
        pass = list(test_two_options_pass_1 = list(long = "test if two options are correctly recognized - pass 1", 
            sct = "test_yaml_header(options = c(\"title\", \"output\"))"))), list(type = "MarkdownExercise", 
        student = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: html_document\n---\n    \n    This\n    is\n    a\n    test\n    \n    ```{r}\n    dim(cars)\n    ```", 
        solution = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: html_document\n---\n    \n    This\n    is\n    a\n    test\n    but\n    doesn't \n    matter\n    \n    ```{r}\n    str(cars)\n    ```", 
        pass = list(test_three_options_pass_1 = list(long = "test if three options are correctly recognized - pass 1", 
            sct = "test_yaml_header(options = c(\"title\", \"output\", \"author\"))"))), list(type = "MarkdownExercise", 
        student = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: html_document\ninput: html_document\nthis:\n  is:\n    a:\n      complex:\n        test: true\n      simple:\n        test: false\n    irrelevant: true\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ninput: html_document\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: html_document\nthis:\n  is:\n    a:\n      complex:\n        test: true\n      simple:\n        test: false\n---\n    \n    This\n    is\n    a\n    test\n    but\n    doesn't \n    matter\n    \n    ```{r}\n    str(cars)\n    ```", 
        pass = list(test_complex_options_pass_1 = list(long = "test if complex options are correctly recognized - pass 1", 
            sct = "test_yaml_header(options = c(\"title\", \"input\", \"output\", \"author\"))"), test_complex_options_pass_2 = list(long = "test if complex options are correctly recognized - pass 2", 
            sct = "test_yaml_header(options = \"this.is.a.complex.test\")"), test_complex_options_pass_3 = list(long = "test if complex options are correctly recognized - pass 3", 
            sct = "test_yaml_header(options = \"this.is.a.simple.test\")"))), list(type = "MarkdownExercise", 
        student = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: html_document\ninput: html_document\nextra: nevermind\nother: something\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ninput: html_document\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: html_document\nother: something_else\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n    matter\n    \n    ```{r}\n    str(cars)\n    ```", 
        pass = list(test_allow_extra_pass_1 = list(long = "test if allow_extra works correctly - pass 1", sct = "test_yaml_header(options = c(\"title\", \"input\", \"output\", \"author\"))"))), 
    list(type = "MarkdownExercise", student = "\n---\ntitle: \"Testing\"\nauthor: \"Testerke 2\"\noutput: html_document\ninput: html_document\nextra: nevermind\nother: something\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ninput: html_document\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: html_document\nother: something_else\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n  matter\n  \n  ```{r}\n  str(cars)\n  ```", 
        pass = list(test_check_equality_pass_1 = list(long = "test if check_equality works correctly - pass 1", 
            sct = "test_yaml_header(options = c(\"title\", \"input\", \"output\"))"), test_check_equality_pass_2 = list(long = "test if check_equality works correctly - pass 2", 
            sct = "test_yaml_header(options = \"author\", check_equality = FALSE)"))), list(type = "MarkdownExercise", 
        student = "\n---\ntitle: \"Wrong\"\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ntitle: \"Testing\"\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n  matter\n  \n  ```{r}\n  str(cars)\n  ```", 
        fail = list(test_one_option_fails_fail_1 = list(long = "test if one option fails correctly - fail 1", 
            sct = "test_yaml_header(options = c(\"title\"))"))), list(type = "MarkdownExercise", student = "\n---\ntitle: \"Wrong\"\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ntitle: \"Testing\"\noutput: html_document\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n  matter\n  \n  ```{r}\n  str(cars)\n  ```", 
        fail = list(test_two_options_fail_fail_1 = list(long = "test if two options fail correctly - fail 1", 
            sct = "test_yaml_header(options = c(\"title\", \"output\"))"), test_two_options_fail_fail_2 = list(long = "test if two options fail correctly - fail 2", 
            sct = "test_yaml_header(options = \"title\")"), test_two_options_fail_fail_3 = list(long = "test if two options fail correctly - fail 3", 
            sct = "test_yaml_header(options = \"output\")"))), list(type = "MarkdownExercise", student = "\n---\ntitle: \"Wrong\"\nauthor: \"Not right\"\noutput: pdf_document\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: html_document\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n  matter\n  \n  ```{r}\n  str(cars)\n  ```", 
        fail = list(test_three_options_fail_fail_1 = list(long = "test if three options fail correctly - fail 1", 
            sct = "test_yaml_header(options = c(\"title\", \"output\", \"author\"))"), test_three_options_fail_fail_2 = list(long = "test if three options fail correctly - fail 2", 
            sct = "test_yaml_header(options = c(\"title\", \"output\"))"), test_three_options_fail_fail_3 = list(long = "test if three options fail correctly - fail 3", 
            sct = "test_yaml_header(options = \"title\")"), test_three_options_fail_fail_4 = list(long = "test if three options fail correctly - fail 4", 
            sct = "test_yaml_header(options = \"output\")"), test_three_options_fail_fail_5 = list(long = "test if three options fail correctly - fail 5", 
            sct = "test_yaml_header(options = \"author\")"))), list(type = "MarkdownExercise", student = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: \n  html_document:\n    test: true\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: \n  html_document:\n    test: false\n  pdf_document:\n    test: true\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n  matter\n  \n  ```{r}\n  str(cars)\n  ```", 
        fail = list(test_complex_options_fail_fail_1 = list(long = "test if complex options fail correctly - fail 1", 
            sct = c("test_yaml_header(options = c(\"title\", \"output.html_document.test\", ", "    \"author\", \"output.pdf_document.test\"))")), 
            test_complex_options_fail_fail_2 = list(long = "test if complex options fail correctly - fail 2", 
                sct = "test_yaml_header(options = c(\"title\", \"author\", \"output.pdf_document.test\"))"), 
            test_complex_options_fail_fail_3 = list(long = "test if complex options fail correctly - fail 3", 
                sct = "test_yaml_header(options = c(\"output.pdf_document.test\"))"))), list(type = "MarkdownExercise", 
        student = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: \n  html_document:\n    test: true\n  extra: \"NOOO\"\n  pdf_document:\n    test: true\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ntitle: \"Testing\"\nauthor: \"Tester\"\noutput: \n  html_document:\n    test: false\n  pdf_document:\n    test: true\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n  matter\n  \n  ```{r}\n  str(cars)\n  ```", 
        fail = list(test_allow_extra_fail_fail_1 = list(long = "test if allow_extra fails correctly - fail 1", 
            sct = c("test_yaml_header(options = c(\"title\", \"output.html_document.test\", ", "    \"author\"), allow_extra = FALSE)")), 
            test_allow_extra_fail_fail_2 = list(long = "test if allow_extra fails correctly - fail 2", sct = c("test_yaml_header(options = c(\"title\", \"author\", \"output.pdf_document.test\"), ", 
                "    allow_extra = FALSE)")), test_allow_extra_fail_fail_3 = list(long = "test if allow_extra fails correctly - fail 3", 
                sct = "test_yaml_header(options = c(\"output.pdf_document.test\"), allow_extra = FALSE)"))), 
    list(type = "MarkdownExercise", student = "\n---\ntitle: \"Testing\"\noutput: \n  html_document:\n    test: true\n    extra: \"NOOO\"\n  pdf_document:\n    test: true\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ntitle: \"Tersting\"\noutput: \n  html_document:\n    test: true\n    extra: \"NOOO\"\n  pdf_document:\n    test: true\nauthor: \"Tester\"\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n  matter\n  \n  ```{r}\n  str(cars)\n  ```", 
        fail = list(test_check_equality_fail_fail_1 = list(long = "test if check_equality fails correctly - fail 1", 
            sct = c("test_yaml_header(options = c(\"title\", \"output.html_document.test\", ", "    \"author\"), check_equality = FALSE)")), 
            test_check_equality_fail_fail_2 = list(long = "test if check_equality fails correctly - fail 2", 
                sct = "test_yaml_header(options = c(\"author\"), check_equality = FALSE)"))), list(type = "MarkdownExercise", 
        student = "\n---\ntitle: \"Testing\"\ntitle: \"OOPS\"\n---\n  \n  This\n  is\n  a\n  test\n  \n  ```{r}\n  dim(cars)\n  ```", 
        solution = "\n---\ntitle: \"OOPS\"\n---\n  \n  This\n  is\n  a\n  test\n  but\n  doesn't \n  matter\n  \n  ```{r}\n  str(cars)\n  ```", 
        fail = list(test_yaml_structure_error_fail_1 = list(long = "test if check_equality fails correctly - fail 1", 
            sct = "test_yaml_header(options = c(\"title\"))"))))
