#' Combine tests
#' 
#' \code{test_correct} checks whether a set of tests passes, and do additional, more precise tests if there
#' were failures. The teacher should specify two code chunks; \itemize{ 
#' \item{\code{check_code}: specifies the code that checks on the (typically,
#' final results of the) student's code. These tests are executed silently,
#' without the reporter generating information for these.} 
#' \item{\code{diagnose_code}: Set of tests that gets executed if the tests in
#' \code{check_code} fail. These tests contain more detailed tests, to pinpoint
#' the problem.} }
#' 
#' \code{test_correct} increases the flexibility for the student: if the tests 
#' in \code{check_code} pass, the results of the tests in \code{diagnose_code}
#' are not considered. If you test for the end result in \code{check_code}, and
#' only do more rigorous testing in \code{diagnose_code}, you can allow for
#' multiple solutions to a challenge.
#' 
#' Similarly, \code{test_or} checks whether one of many test sets pass. That way, you can allow for multiple solutions
#' 
#' @param check_code In \code{test_correct}, tests that are always run.
#' @param diagnose_code In \code{test_correct}, tests that are run only if the tests in \code{check_code} fail.
#' @param ... a set of tests passed to \code{test_or}, each set separated by a comma. Only one of these tests should pass
#' @param incorrect_msg In \code{test_or} chracter string to override message generated by the failing test block.
#' @param choose_feedback If all tests fail in \code{test_or} , selects the feedback of the set of tests that should be shown
#' 
#' @examples
#' \dontrun{
#' # Example 1 solution code
#' x <- mean(1:3)
#' 
#' # Example SCT
#' test_correct(
#'   ex() %>% check_object("x") %>% check_equal(),
#'   ex() %>% check_fun("mean") %>% check_arg("x") %>% check_equal()
#' )
#' 
#' # Following submissions will all be accepted:
#' x <- mean(1:3)
#' x <- 2
#' x <- mean(-1:5)
#' 
#' 
#' # Example 2 solution code
#' # a <- 3; b <- 4
#' 
#' # Example SCT
#' test_or(
#'   ex() %>% check_object('a') %>% check_equal(),
#'   ex() %>% check_object('b') %>% checK-equal()
#' )
#' 
#' # Following submissions will all be accepted:
#' a <- 3; b <- 4
#' a <- 3
#' b <- 4
#' }
#' 
#' @rdname check_logic

#' @rdname check_logic
#' @export
test_correct <- function(check_code, diagnose_code) {
  check_res <- run_until_fail(substitute(check_code))
  diagnose_res <- run_until_fail(substitute(diagnose_code))
  if (check_res$correct) {
    # all good
  } else {
    if (diagnose_res$correct) {
      check_that(failure(), feedback = check_res$feedback)
    } else {
      check_that(failure(), feedback = diagnose_res$feedback)
    }
  }
}

#' @rdname check_logic
#' @export
test_or <- function(..., incorrect_msg = NULL, choose_feedback = 1) {

  input <- substitute(alist(...))
  input[[1]] <- NULL
  
  passes <- logical(length(input) )
  feedback <- list()
  
  for (i in seq_along(input)) {
    code <- input[[i]]
    res <- run_until_fail(code)
    passes[i] <- res$correct
    feedback[[i]] <- res$feedback
  }
  
  if (!any(passes)) {
    if (is.null(incorrect_msg)) {
      check_that(failure(), feedback = feedback[[choose_feedback]])
    } else {
      check_that(failure(), feedback = incorrect_msg)
    }
  }
}

# Deprecated

check_correct <- test_correct
check_or <- test_or