#' Run all tests for an exercise
#'
#' Run all tests for an exercise and report the results (including feedback).
#' This function is run by R Backend and should not be used by course creators.
#'
#' @param sct Submission correctness tests as a character string.
#' @param ex_type Type of the exercise
#' @param pec pre-exercise-code
#' @param student_code character string representing the student code
#' @param solution_code character string representing the solution code
#' @param solution_env environment containing the objects defined by solution code
#' @param output_list the output structure that is generated by RBackend
#' @param env  environment in which to execute tests.
#'
#' @return A list with components \code{passed} that indicates whether all
#' tests were sucessful, and \code{feedback} that contains a feedback message.
#'
#' @export
test_exercise <- function(sct, 
                          ex_type, 
                          pec,
                          student_code,
                          solution_code,
                          solution_env,
                          output_list,
                          env = test_env()) {
  
  # Store everything that's needed locally
  tw$initialize(list(pec = pec,
                     student_code = student_code,
                     student_pd = try(getParseData(parse(text = student_code, keep.source = TRUE), includeText = TRUE)),
                     student_env = globalenv(),
                     solution_code = solution_code,
                     solution_pd = try(getParseData(parse(text = student_code, keep.source = TRUE), includeText = TRUE)),
                     solution_env = solution_env,
                     output_list = output_list))
  
  # Execute sct with the DataCamp reporter such that it collects test results
  reporter <- DataCampReporter$new(ex_type=ex_type)
  with_reporter(reporter, .test_exercise(parse(text = sct), env))

  # Obtain feedback from DataCamp reporter and return it invisibly
  reporter$get_feedback()
}

.test_exercise <- function(code, parent_env) {
  get_reporter()$start_reporter()
  n <- length(code)
  if (n == 0L) return(invisible())
  run_until_fail(code, parent_env)
}

run_until_fail <- function(code, env) {
  eval_fail <- try(eval(code, envir = env), silent = TRUE)
  if (inherits(eval_fail, "try-error")) {
    cond <- attr(eval_fail, "condition")$message
    if (identical(cond, sct_failed_msg)) {
      # The SCT failed
      return(invisible())
    } else {
      # Something actually went wrong, not an SCT that failed
      stop(attr(eval_fail, "condition"))
    }
  } else {
    # The SCT passed
    return(invisible())
  }
}