#' Check whether the student's submission threw an error.
#'
#' With information gathered from the R Backend, \code{test_error} detects
#' whether the student's submission generated an error. Automatically, a feedback is generated,
#' which can be appended with an additional incorrect_msg.
#'
#' @param incorrect_msg feeback message that is appended to the error message generated by R.
#'
#' @examples
#' \dontrun{
#' # Example student code: x <- 4 + "a"
#' 
#' # R error message as feedback:
#' test_error()
#' 
#' # R error message as feedback, with additional info:
#' test_error("Don't sum numerics and characters!")
#' }
#'
#' @import datacampAPI
#' @import testthat
#' @export
test_error <- function(incorrect_msg = NULL) {
  output_list <- tw$get("output_list")
  errors =  sapply(output_list, function(x) { if(x$type == "r-error") return(x$payload) })
  errors[sapply(errors, is.null)] <- NULL
  if(length(errors) == 0) {
    build_msg <- "all good"
  } else {
    build_msg <- sprintf("Your solution contains an error:<br><i>%s</i>%s", 
                         errors[[1]],
                         ifelse(is.null(incorrect_msg), "", paste0("<br>",incorrect_msg)))
  }
  test_what(expect_true(length(errors) == 0), feedback_msg = build_msg)
}