#' Check whether the student's submission threw an error.
#'
#' With information gathered from the R Backend, \code{test_error} detects
#' whether the student's submission generated an error. Automatically, a feedback is generated,
#' which can be appended with an additional incorrect_msg.
#'
#' @param incorrect_msg feeback message that is appended to the error message generated by R.
#' @param error The error message if the student's submission generated one; 
#' NULL if there was no error. Do not set this manually.
#'
#' @examples
#' \dontrun{
#' # Example student code: x <- 4 + "a"
#' 
#' # R error message as feedback:
#' test_error()
#' 
#' # R error message as feedback, with additional info:
#' test_error("Don't sum numerics and characters!")
#' }
#'
#' @import datacampAPI
#' @import testthat
#' @export
test_error <- function(incorrect_msg = NULL, error = get_student_error()) {
  build_msg = sprintf("Your solution contains an error:<br><i>%s</i>%s", 
                      error,
                      ifelse(is.null(incorrect_msg), "", paste0("<br>",incorrect_msg)))
  
  test_what(expect_null(error), build_msg)
}